version: "3.9"
services:
        web:
                build: .
                ports:
                        - "5000:5000"
                volumes:
                        - ./saved_dictionaries_freiburg:/code/saved_dictionaries_freiburg:ro
                        - ./GTFS:/code/GTFS:ro
