/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// Thanks to https://www.freecodecamp.org/news/
///             how-to-add-custom-icons-to-your-flutter-application/
/// for the tutorial
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData funicular = IconData(
      0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cable_car = IconData(
      0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monorail = IconData(
      0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gondola = IconData(
      0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trolleybus = IconData(
      0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
